//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        public int ID { get; set; }
        public Nullable<int> LogID { get; set; }
        public string Title { get; set; }
        public string Entry1 { get; set; }
        public int OwnerID { get; set; }
    
        public virtual User User { get; set; }
    }
}
