//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagedView
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string IPAddress { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string ActionParameters { get; set; }
        public string AbsoluteUri { get; set; }
        public string Notes { get; set; }
    }
}
