//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOwner
    {
        public int ID { get; set; }
        public Nullable<int> LogID { get; set; }
        public Nullable<int> DomID { get; set; }
        public Nullable<int> SubID { get; set; }
        public Nullable<int> RequestByID { get; set; }
        public Nullable<int> ApprovedByID { get; set; }
        public Nullable<System.DateTime> RequestTime { get; set; }
        public Nullable<System.DateTime> ApprovedTime { get; set; }
        public Nullable<int> Rejected { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User11 { get; set; }
        public virtual User User3 { get; set; }
    }
}
